version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bot
    ports:
      - '8443:8443'
    volumes:
      - /tmp/deploy/prod/.env:/src/.env:ro
      - /tmp/downloads/:/tmp/downloads/:rw
      - /tmp/bot/persistence/:/tmp/bot/persistence/:rw
      - /tmp/instaloader/:/tmp/instaloader/:rw
  auth:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: auth
    command: ["instaloader -l amaprograma -f /tmp/instaloader/session-amaprograma"]
    volumes:
      - /tmp/instaloader/:/tmp/instaloader/:rw
