version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bot
    ports:
      - '8443:8443'
    volumes:
      - /var/reelsbot/settings/:/var/reelsbot/settings/
      - /var/reelsbot/.env:/src/.env
