version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bot
    ports:
      - '8443:8443'
    volumes:
      - /var/config/prod.env:/src/.env:ro
      - /var/config/settings.json:/var/deploy/settings.json
