version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bot
    ports:
      - '8443:8443'
    volumes:
      - type: bind
        source: /var/reelsbot/.env
        target: /src/.env:ro
      - type: bind
        source: /var/reelsbot/settings.json
        target: /var/reelsbot/settings.json
