version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bot
    ports:
      - '8443:8443'
    volumes:
      - /var/deploy/prod/.env:/src/.env:ro
      - /var/deploy/prod/.settings:/var/deploy/prod/.settings
